'\" t
.\" @(#)icedax.1	1.14 02/12/09 Copyright 1998,1999,2000 Heiko Eissfeldt
.if t .ds a \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'a
.if t .ds o \v'-0.55m'\h'0.00n'\z.\h'0.45n'\z.\v'0.55m'\h'-0.45n'o
.if t .ds u \v'-0.55m'\h'0.00n'\z.\h'0.40n'\z.\v'0.55m'\h'-0.40n'u
.if t .ds A \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'A
.if t .ds O \v'-0.77m'\h'0.25n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.70n'O
.if t .ds U \v'-0.77m'\h'0.30n'\z.\h'0.45n'\z.\v'0.77m'\h'-0.75n'U
.if t .ds s \\(*b
.if t .ds S SS
.if n .ds a ae
.if n .ds o oe
.if n .ds u ue
.if n .ds s sz
.if t .ds m \\(*m
.if n .ds m micro
.TH ICEDAX 1
.SH NAME
icedax \- a sampling utility that dumps CD audio data into wav sound
files
.SH SYNOPSIS
.B icedax
.RB [ -c
.IR chans ]
.RB [ -s ]
.RB [ -m ]
.RB [ -b
.IR bits ]
.RB [ -r
.IR rate ]
.RB [ -a
.IR divider ]
.RB [ -t
.IR track [ +endtrack ]]
.RB [ -i
.IR index ]
.RB [ -o
.IR offset ]
.RB [ -d
.IR duration ]
.RB [ -x ]
.RB [ -q ]
.RB [ -w ]
.RB [ -v
.IR optlist ]
.RB [ -V ]
.RB [ -Q ]
.RB [ -J ]
.RB [ -L
.IR cddbmode ]
.RB [ -R ]
.RB [ -P
.IR sectors ]
.RB [ -F ]
.RB [ -G ]
.RB [ -T ]
.RB [ -e ]
.RB [ -p
.IR percentage ]
.RB [ -n
.IR sectors ]
.RB [ -l
.IR buffers ]
.RB [ -N ]
.RB [ -J ]
.RB [ -H ]
.RB [ -g ]
.RB [ -B ]
.RB [ -D
.IR device ]
.RB [ -A
.IR auxdevice ]
.RB [ -I
.IR interface ]
.RB [ -O
.IR audiotype ]
.RB [ -C
.IR input-endianess ]
.RB [ -E
.IR output-endianess ]
.RB [ -M
.IR count ]
.RB [ -S
.IR speed ]
.RB [ -paranoia ]
.RB [ cddbp-server=servername ]
.RB [ cddbp-port=portnumber ]
.RI [ filename(s)
or
.IR directories ]
.SH DESCRIPTION
.B icedax
stands for InCrEdible Digital Audio eXtractor. It can retrieve audio tracks
.RB ( CDDA )
from CDROM drives
that are
capable of reading audio data digitally to the host
(see README for a list of drives).

.SH OPTIONS
.TP
.BI dev= device
.TP
.BI \-D " device
.TP
.BI \-device " device
uses
.B device
as the source for CDDA reading. For example
.B /dev/cdrom
or
.B Bus,ID,Lun.
The device specification can also have influence on the selection of the driver interface (eg. on Linux).
See the
.B \-I
option for details.
.sp
The setting of the environment variable
.B CDDA_DEVICE
is overridden by this option.
.TP
.BI \-A " auxdevice
.TP
.BI \-auxdevice " auxdevice
uses
.B auxdevice
as CDROM drive for ioctl usage.
.TP
.BI \-I " interface
.TP
.BI \-interface " interface
specifies the interface for CDROM access:
.B generic_scsi
or (on Linux, and FreeBSD systems)
.BR cooked_ioctl .
.sp
Using the
.B cooked_ioctl
is not recommended as this makes
.B icedax
mainly depend on the audio extraction quality of the operating system
which is usually extremely bad.
.TP
.BI \-c " channels  --channels"
uses
.B 1
for mono, or
.B 2
for stereo recording,
or
.B s
for stereo recording with both channels swapped.
.TP
.B \-s " --stereo"
sets to stereo recording.
.TP
.B \-m " --mono"
sets to mono recording.
.TP
.B \-x " --max"
sets maximum (CD) quality.
.TP
.BI \-b " bits  --bits-per-sample"
sets bits per sample per channel:
.BR 8 ,
.B 12
or
.BR 16 .
.TP
.BI \-r " rate  --rate"
sets rate in samples per second.  Possible values are listed with the
.B \-R
option.
.TP
.BI \-a " divider  --divider"
sets rate to 44100Hz / divider.  Possible values are listed with the
.B \-R
option.
.TP
.B \-R " --dump-rates"
shows a list of all sample rates and their dividers.
.TP
.B \-P " sectors  --set-overlap"
sets the initial number of overlap
.I sectors
for jitter correction.
.TP
.BI \-n " sectors  --sectors-per-request"
reads 
.I sectors
per request.
.TP
.BI \-l " buffers  --buffers-in-ring"
uses a ring buffer with 
.I buffers
total.
.TP
.BI \-t " track+endtrack  --track"
selects the start track and optionally the end track.
.TP
.BI \-i " index  --index"
selects the start index.
.TP
.BI \-o " offset  --offset"
starts
.I offset
sectors behind start track (one sector equivalents 1/75 seconds).
.TP
.B \-O " audiotype  --output-format"
can be 
.I wav
(for wav files) or
.I aiff
(for apple/sgi aiff files) or
.I aifc
(for apple/sgi aifc files) or
.I au
or
.I sun
(for sun .au PCM files) or
.I cdr
or
.I raw
(for headerless files to be used for cd writers).
.TP
.BI \-C " endianess  --cdrom-endianess"
sets endianess of the input samples to 'little', 'big' or 'guess' to override defaults.
.TP
.BI \-E " endianess  --output-endianess"
sets endianess of the output samples to 'little' or 'big' to override defaults.
.TP
.BI \-d " duration  --duration"
sets recording time in seconds or frames.
Frames (sectors) are indicated by a 'f' suffix (like 75f for 75 sectors).
.B 0
sets the time for whole track.
.TP
.B \-B " --bulk --alltracks"
copies each track into a separate file.
.TP
.B \-w " --wait"
waits for signal, then start recording.
.TP
.B \-F " --find-extremes"
finds extreme amplitudes in samples.
.TP
.B \-G " --find-mono"
finds if input samples are in mono.
.TP
.B \-T " --deemphasize"
undo the effect of pre-emphasis in the input samples.
.TP
.B \-e " --echo"
copies audio data to sound device e.g.
.BR /dev/dsp .
.TP
.B \-p " percentage --set-pitch"
changes pitch of audio data copied to sound device.
.TP
.B \-v " itemlist  --verbose-level"
prints verbose information about the CD.
.B Level
is a list of comma separated suboptions. Each suboption controls the type of information to be reported.
.TS H
allbox;
c cw(1i)
r l.
Suboption	Description
disable	no information is given, warnings appear however
all	all information is given
toc	show table of contents
summary	show a summary of the recording parameters
indices	determine and display index offsets
catalog	retrieve and display the media catalog number MCN
trackid	T{
.na
retrieve and display all International Standard Recording Codes ISRC
T}
sectors	T{
.na
show the table of contents in start sector notation
T}
titles	T{
.na
show the table of contents with track titles (when available)
T}
.TE
.TP
.B \-N " --no-write"
does not write to a file, it just reads (for debugging purposes).
.TP
.B \-J " --info-only"
does not write to a file, it just gives information about the disc.
.TP
.B \-L " cddb mode --cddb"
does a cddbp album- and track title lookup based on the cddb id.
The parameter cddb mode defines how multiple entries shall be handled.
.TS H
allbox;
c cw(4i)
r l.
Parameter	Description
0	T{
.na
interactive mode. The user selects the entry to use.
T}
1	T{
.na
first fit mode. The first entry is taken unconditionally.
T}
.TE
.TP
.B " cddbp-server=servername"
sets the server to be contacted for title lookups.
.TP
.B " cddbp-port=portnumber"
sets the port number to be used for title lookups.
.TP
.B \-H " --no-infofile"
does not write an info file and a cddb file.
.TP
.B \-g " --gui"
formats the output to be better parsable by gui frontends.
.TP
.B \-M " count --md5"
enables calculation of MD-5 checksum for 'count' bytes from a beginning of a
track.
.TP
.B \-S " speed --speed"
sets the cdrom device to one of the selectable speeds for reading.
.TP
.B \-q " --quiet"
quiet operation, no screen output.
.TP
.B \-V " --verbose-SCSI"
enable SCSI command logging to the console. This is mainly used for debugging.
.TP
.B \-Q " --silent-SCSI"
suppress SCSI command error reports to the console. This is mainly used for guis.
.TP
.B \-scanbus
Scan all SCSI devices on all SCSI busses and print the inquiry
strings. This option may be used to find SCSI address of the 
CD/DVD-Recorder on a system.
The numbers printed out as labels are computed by: 
.B "bus * 100 + target
.TP
.B \-\-devices
Like \-scanbus but works in a more native way, respecting the device name
specification on the current operating system. See
.B wodim(1)
for details.
.TP
.B \-paranoia
use the paranoia library instead of icedax's routines for reading.
.TP
.B \-h " --help"
display version of icedax on standard output.
.TP
Defaults depend on the
.B Makefile
and
.B environment variable
settings (currently
.B CDDA_DEVICE
).
.SH "ENVIRONMENT VARIABLES"
.B CDDA_DEVICE
is used to set the device name. The device naming is compatible with the one
used by the wodim tool.
.TP
.B CDDBP_SERVER
is used for cddbp title lookups when supplied.
.TP
.B CDDBP_PORT
is used for cddbp title lookups when supplied.
.TP
.B RSH
If the 
.B RSH
environment variable is present, the remote connection will not be created via
.BR rcmd (3)
but by calling the program pointed to by
.BR RSH .
Use e.g. 
.BR RSH= /usr/bin/ssh
to create a secure shell connection.
.sp
Note that this forces 
.B icedax
to create a pipe to the 
.B rsh(1)
program and disallows
.B icedax
to directly access the network socket to the remote server.
This makes it impossible to set up performance parameters and slows down
the connection compared to a 
.B root
initiated
.B rcmd(3)
connection.
.TP
.B RSCSI
If the 
.B RSCSI
environment variable is present, the remote SCSI server will not be the program
.B /opt/schily/sbin/rscsi
but the program pointed to by
.BR RSCSI .
Note that the remote SCSI server program name will be ignored if you log in
using an account that has been created with a remote SCSI server program as
login shell.
.SH "RETURN VALUES"
.B icedax
uses the following exit codes to indicate various degrees of success:
.TS H
allbox;
c cw(1i)
r l.
Exitcode	Description
0	no errors encountered, successful operation.
1	usage or syntax error. icedax got inconsistent arguments.
2	permission (un)set errors. permission changes failed.
3	read errors on the cdrom/burner device encountered.
4	T{
.na
write errors while writing one of the output files encountered.
T}
5	errors with soundcard handling (initialization/write).
6	T{
.na
errors with stat() system call on the read device (cooked ioctl).
T}
7	pipe communication errors encountered (in forked mode).
8	signal handler installation errors encountered.
9	allocation of shared memory failed (in forked mode).
10	dynamic heap memory allocation failed.
11	errors on the audio cd medium encountered.
12	device open error in ioctl handling detected.
13	race condition in ioctl interface handling detected.
14	error in ioctl() operation encountered.
15	internal error encountered. Please report back!!!
16	T{
.na
error in semaphore operation encountered (install / request).
T}
17	could not get the scsi transfer buffer.
18	T{
.na
could not create pipes for process communication (in forked mode).
T}
.TE
.SH "DISCUSSION"
.B icedax
is able to read parts of an
.B audio
CD or
.B multimedia
CDROM (containing audio parts) directly digitally. These parts can be
written to a file, a pipe, or to a sound device.
.PP
.B icedax
stands for
.B CDDA
to
.B WAV
(where
.B CDDA
stands for compact disc digital audio and
.B WAV
is a sound sample format introduced by MS Windows).  It
allows copying
.B CDDA
audio data from the CDROM drive into a file in 
.B WAV
or other formats.
.PP
The latest versions try to get higher real-time scheduling priorities to ensure
smooth (uninterrupted) operation. These priorities are available for super users
and are higher than those of 'normal' processes. Thus delays are minimized.
.PP
If your CDROM is on device
.B DEV
and it is loaded with an audio CD, you may simply invoke
.B icedax dev=DEV
and it will create the sound file
.B audio.wav
recording the whole track beginning with track 1 in stereo at 16 bit at 44100
Hz sample rate, if your file system has enough space free.  Otherwise
recording time will be limited. For details see files
.B README
and
.B README.INSTALL
.
.SH "HINTS ON OPTIONS"
.IP "Options"
Most of the options are used to control the format of the WAV file. In
the following text all of them are described.
.IP "Select Device"
.BI \-D " device"
selects the CDROM drive device to be used.
The specifier given should correspond to the selected interface (see below).
.B CHANGE!
For the cooked_ioctl interface this is the cdrom device descriptor as before.
.B The SCSI devices used with the generic SCSI interface however are now
.B addressed with their SCSI-Bus, SCSI-Id, and SCSI-Lun instead of the generic
.B SCSI device descriptor!!!
One example for a SCSI CDROM drive on bus 0 with SCSI ID 3 and lun 0 is -D0,3,0.
.IP "Select Auxiliary device"
.BI \-A " auxdevice"
is necessary for CD-Extra handling. For Non-SCSI-CDROM drives this is the
same device as given by -D (see above). For SCSI-CDROM drives it is the
CDROM drive (SCSI) device (i.e.  
.B /dev/sr0
) corresponding to the SCSI device (i.e.
.B 0,3,0
). It has to match the device used for sampling.
.IP "Select Interface"
.BI \-I " interface"
selects the CDROM drive interface. For SCSI drives use generic_scsi
(cooked_ioctl may not yet be available for all devices):
.B generic_scsi
and
.BR cooked_ioctl .
The first uses the generic SCSI interface, the latter uses the ioctl of
the CDROM driver. The latter variant works only when the kernel driver supports
.B CDDA
reading. This entry has to match the selected CDROM device (see above).
.IP "Enable echo to soundcard"
.B \-e
copies audio data to the sound card while recording, so you hear it nearly
simultaneously. The soundcard gets the same data that is recorded. This
is time critical, so it works best with the
.B \-q
option.  To use
.B icedax
as a pseudo CD player without recording in a file you could use
.B "icedax \-q \-e \-t2 \-d0 \-N"
to play the whole second track. This feature reduces the recording speed
to at most onefold speed. You cannot make better recordings than your sound card
can play (since the same data is used).
.IP "Change pitch of echoed audio"
.B "\-p percentage"
changes the pitch of all audio echoed to a sound card. Only the copy
to the soundcard is affected, the recorded audio samples in a file
remain the same.
Normal pitch, which is the default, is given by 100%.
Lower percentages correspond to lower pitches, i.e.
-p 50 transposes the audio output one octave lower.
See also the script
.B pitchplay
as an example. This option was contributed by Raul Sobon.
.IP "Select mono or stereo recording"
.B \-m
or
.B "\-c 1"
selects mono recording (both stereo channels are mixed),
.B \-s
or
.B "\-c 2"
or
.B "\-c s"
selects stereo recording. Parameter s
will swap both sound channels.
.IP "Select maximum quality"
.B \-x
will set stereo, 16 bits per sample at 44.1 KHz (full CD quality).  Note
that other format options given later can change this setting.
.IP "Select sample quality"
.B "\-b 8"
specifies 8 bit (1 Byte) for each sample in each channel;
.B "\-b 12"
specifies 12 bit (2 Byte) for each sample in each channel;
.B "\-b 16"
specifies 16 bit (2 Byte) for each sample in each channel (Ensure that
your sample player or sound card is capable of playing 12-bit or 16-bit
samples). Selecting 12 or 16 bits doubles file size.  12-bit samples are
aligned to 16-bit samples, so they waste some disk space.
.IP "Select sample rate"
.BI \-r " samplerate"
selects a sample rate.
.I samplerate
can be in a range between 44100 and 900. Option
.B \-R
lists all available rates.
.IP "Select sample rate divider"
.BI \-a " divider"
selects a sample rate divider.
.I divider
can be minimally 1 and maximally 50.5 and everything between in steps of 0.5.
Option
.B \-R
lists all available rates.
.IP
To make the sound smoother at lower sampling rates,
.B icedax
sums over
.I n
samples (where
.I n
is the specific dividend). So for 22050 Hertz output we have to sum over
2 samples, for 900 Hertz we have to sum over 49 samples.  This cancels
higher frequencies. Standard sector size of an audio CD (ignoring
additional information) is 2352 Bytes. In order to finish summing
for an output sample at sector boundaries the rates above have to be
chosen.  Arbitrary sampling rates in high quality would require some
interpolation scheme, which needs much more sophisticated programming.
.IP "List a table of all sampling rates"
.BI \-R
shows a list of all sample rates and their dividers. Dividers can range
from 1 to 50.5 in steps of 0.5.
.IP "Select start track and optionally end track"
.BI \-t " n+m"
selects
.B n
as the start track and optionally
.B m
as the last track of a range to be recorded.
These tracks must be from the table of contents.  This sets
the track where recording begins. Recording can advance through the
following tracks as well (limited by the optional end track or otherwise
depending on recording time). Whether one file or different files are
then created depends on the
.B \-B
option (see below).
.IP "Select start index"
.BI \-i " n"
selects the index to start recording with.  Indices other than 1 will
invoke the index scanner, which will take some time to find the correct
start position. An offset may be given additionally (see below).
.IP "Set recording time"
.B \-d " n"
sets recording time to
.I n
seconds or set recording time for whole track if
.I n
is zero. In order to specify the duration in frames (sectors) also, the
argument can have an appended 'f'. Then the numerical argument is to be
taken as frames (sectors) rather than seconds.
Please note that if track ranges are being used they define the recording
time as well thus overriding any
.BR \-d " option"
specified times.
.IP
Recording time is defined as the time the generated sample will play (at
the defined sample rate). Since it's related to the amount of generated
samples, it's not the time of the sampling process itself (which can be
less or more).  It's neither strictly coupled with the time information on
the audio CD (shown by your hifi CD player).
Differences can occur by the usage of the
.B \-o
option (see below). Notice that recording time will be shortened, unless
enough disk space exists. Recording can be aborted at anytime by
pressing the break character (signal SIGQUIT).
   .IP "Record all tracks of a complete audio CD in separate files"
.B \-B
copies each track into a separate file. A base name can be given. File names
have an appended track number and an extension corresponding to the audio
format. To record all audio tracks of a CD, use a sufficient high duration
(i.e. -d99999).
.IP "Set start sector offset"
.BI \-o " sectors"
increments start sector of the track by
.IR sectors .
By this option you are able to skip a certain amount at the beginning of
a track so you can pick exactly the part you want. Each sector runs for 1/75
seconds, so you have very fine control. If your offset is so high that
it would not fit into the current track, a warning message is issued
and the offset is ignored.  Recording time is not reduced.  (To skip
introductory quiet passages automagically, use the
.B \-w
option see below.)
.IP "Wait for signal option"
.B \-w
Turning on this option will suppress all silent output at startup,
reducing possibly file size.
.B icedax
will watch for any signal in the output signal and switches on writing
to file.
.IP "Find extreme samples"
.B \-F
Turning on this option will display the most negative and the most positive
sample value found during recording for both channels. This can be useful
for readjusting the volume. The values shown are not reset at track
boundaries, they cover the complete sampling process. They are taken from
the original samples and have the same format (i.e. they are independent
of the selected output format).
.IP "Find if input samples are in mono"
.B \-G
If this option is given, input samples for both channels will be compared. At
the end of the program the result is printed. Differences in the channels
indicate stereo, otherwise when both channels are equal it will indicate mono.
.IP "Undo the pre-emphasis in the input samples"
.B \-T
Some older audio CDs are recorded with a modified frequency response called
pre-emphasis. This is found mostly in classical recordings. The correction
can be seen in the flags of the Table Of Contents often. But there are
recordings, that show this setting only in the subchannels. If this option
is given, the index scanner will be started, which reads the q-subchannel
of each track. If pre-emphasis is indicated in the q-subchannel of a track,
but not in the TOC, pre-emphasis will be assumed to be present, and
subsequently a reverse filtering is done for this track before the samples
are written into the audio file.
.IP "Set audio format"
.B \-O " audiotype"
can be 
.I wav
(for wav files) or
.I au
or
.I sun
(for sun PCM files) or
.I cdr
or
.I raw
(for headerless files to be used for cd writers).
All file samples are coded in linear pulse code modulation (as done
in the audio compact disc format). This holds for all audio formats.
Wav files are compatible to Wind*ws sound files, they have lsb,msb byte order
as being used on the audio cd. The default filename extension is '.wav'.
Sun type files are not like the older common logarithmically coded .au files,
but instead as mentioned above linear PCM is used. The byte order is msb,lsb
to be compatible. The default filename extension is '.au'.
The AIFF and the newer variant AIFC from the Apple/SGI world store their samples
in bigendian format (msb,lsb). In AIFC no compression is used.
Finally the easiest 'format',
the cdr aka raw format. It is done per default in msb,lsb byte order to satisfy
the order wanted by most cd writers. Since there is no header information in this
format, the sample parameters can only be identified by playing the samples
on a soundcard or similar. The default filename extension is '.cdr' or '.raw'.
.IP "Select cdrom drive reading speed"
.B \-S " speed"
allows to switch the cdrom drive to a certain level of speed in order to
reduce read errors. The argument is transfered verbatim to the drive.
Details depend very much on the cdrom drives.
An argument of 0 for example is often the default speed of the drive,
a value of 1 often selects single speed.
.IP "Enable MD5 checksums"
.B \-M " count"
enables calculation of MD-5 checksum for 'count' bytes from the beginning of a
track. This was introduced for quick comparisons of tracks.
.IP "Use Monty's libparanoia for reading of sectors"
.B \-paranoia
selects an alternate way of extracting audio sectors. Monty's library is used
with the following default options:
.sp
PARANOIA_MODE_FULL, but without PARANOIA_MODE_NEVERSKIP
.sp
for details see Monty's libparanoia documentation.
In this case the option
.B \-P
has no effect.
.IP "Do linear or overlapping reading of sectors"
(This applies unless option
.B \-paranoia
is used.)
.B \-P " sectors"
sets the given number of sectors for initial overlap sampling for jitter
correction. Two cases are to be distinguished. For nonzero values,
some sectors are read twice to enable icedax's jitter correction.
If an argument of zero is given, no overlap sampling will be used.
For nonzero overlap sectors icedax dynamically adjusts the setting during
sampling (like cdparanoia does).
If no match can be found, icedax retries the read with an increased overlap.
If the amount of jitter is lower than the current overlapped samples, icedax
reduces the overlap setting, resulting in a higher reading speed.
The argument given has to be lower than the total number of sectors per request
(see option
.I -n
below).
Icedax will check this setting and issues a error message otherwise.
The case of zero sectors is nice on low load situations or errorfree (perfect)
cdrom drives and perfect (not scratched) audio cds.
.IP "Set the transfer size"
.B \-n " sectors"
will set the transfer size to the specified sectors per request.
.IP "Set number of ring buffer elements"
.B \-l " buffers"
will allocate the specified number of ring buffer elements.
.IP "Set endianess of input samples"
.B \-C " endianess"
will override the default settings of the input format.
Endianess can be set explicitly to "little" or "big" or to the automatic
endianess detection based on voting with "guess".
.IP "Set endianess of output samples"
.B \-E " endianess"
(endianess can be "little" or "big") will override the default settings 
of the output format.
.IP "Verbose option"
.B \-v " itemlist"
prints more information. A list allows selection of different
information items.
.sp
.B "disable"
keeps quiet
.sp
.B "toc"
displays the table of contents
.sp
.B "summary"
displays a summary of recording parameters
.sp
.B "indices"
invokes the index scanner and displays start positions of indices
.sp
.B "catalog"
retrieves and displays a media catalog number
.sp
.B "trackid"
retrieves and displays international standard recording codes
.sp
.B "sectors"
displays track start positions in absolute sector notation
.sp
To combine several requests just list the suboptions separated with commas.
.IP "The table of contents"
The display will show the table of contents with number of tracks and
total time (displayed in
.IR mm : ss . hh
format,
.IR mm =minutes,
.IR ss =seconds,
.IR hh "=rounded 1/100 seconds)."
The following list displays track number and track time for each entry.
The summary gives a line per track describing the type of the track.
.sp
.ce 1
.B "track preemphasis copypermitted tracktype chans"
.sp
The
.B track
column holds the track number.
.B preemphasis
shows if that track has been given a non linear frequency response.
NOTE: You can undo this effect with the
.B \-T
option.
.B "copy-permitted"
indicates if this track is allowed to copy.
.B "tracktype"
can be data or audio. On multimedia CDs (except hidden track CDs) 
both of them should be present.
.B "channels"
is defined for audio tracks only. There can be two or four channels.
.IP "No file output"
.B \-N
this debugging option switches off writing to a file.
.IP "No infofile generation"
.B \-H
this option switches off creation of an info file and a cddb file.
.IP "Generation of simple output for gui frontends"
.B \-g
this option switches on simple line formatting, which is needed to support
gui frontends (like xcd-roast).
.IP "Verbose SCSI logging"
.B \-V
this option switches on logging of SCSI commands. This will produce
a lot of output (when SCSI devices are being used).
This is needed for debugging purposes. The format
is the same as being used with the cdrecord program from J\*org Schilling or
the wodim tool. See there for details.
.IP "Quiet option"
.B \-q
suppresses all screen output except error messages.
That reduces cpu time resources.
.IP "Just show information option"
.B \-J
does not write a file, it only prints information about the disc (depending
on the
.B \-v
option). This is just for information purposes.
.SH "CDDBP support"
.IP "Lookup album and track titles option"
.B \-L " cddbp mode"
Icedax tries to retrieve performer, album-, and track titles from a cddbp
server. The default server right now is 'freedb.freedb.org'.
It is planned to have more control over the server handling later.
The parameter defines how multiple entries are handled:
.PP
0	interactive mode, the user chooses one of the entries.
.PP
1	take the first entry without asking.
.IP "Set server for title lookups"
.B cddbp-server " servername"
When using \-L or --cddb, the server being contacted can be set with
this option.
.IP "Set portnumber for title lookups"
.B cddbp-port " portnumber"
When using \-L or --cddb, the server port being contacted can be set with
this option.
.SH "HINTS ON USAGE"
Don't create samples you cannot read. First check your sample player
software and sound card hardware. I experienced problems with very low
sample rates (stereo <= 1575 Hz, mono <= 3675 Hz) when trying to play
them with standard WAV players for sound blaster (maybe they are not
legal in
.B WAV
format). Most CD-Writers insist on audio samples in a bigendian format.
Now icedax supports the 
.B \-E " endianess"
option to control the endianess of the written samples.
.PP
If your hardware is fast enough to run icedax
uninterrupted and your CD drive is one of the 'perfect' ones, you will
gain speed when switching all overlap sampling off with the
.B \-P " 0"
option. Further fine tuning can be done with the
.B \-n " sectors"
option. You can specify how much sectors should be requested in one go.
.PP
Icedax supports
.B pipes
now. Use a filename of
.B \-
to let icedax output its samples to standard output.
.PP
Conversion to other sound formats can be done using the
.B sox
program package (although the use of
.B sox -x
to change the byte order of samples should be no more necessary; see option
.B \-E
to change the output byteorder).
.PP
If you want to sample more than one track into
different files in one run, this is currently possible with the
.B \-B
option. When recording time exceeds the track limit a new file will
be opened for the next track.
.SH FILES
Icedax can generate a lot of files for various purposes.
.sp
Audio files:
.sp
There are audio files containing samples with default extensions
.wav, .au, .aifc, .aiff, and .cdr according to the selected sound format.
These files are not generated when option (-N) is given. Multiple files may
be written when the bulk copy option (-B) is used. Individual file names
can be given as arguments. If the number of file names given is sufficient
to cover all included audio tracks, the file names will be used verbatim.
Otherwise, if there are less file names than files needed to write the
included tracks, the part of the file name before the extension is extended
with '_dd' where dd represents the current track number.
.sp
Cddb and Cdindex files:
.sp
If icedax detects cd-extra or cd-text (album/track) title information,
then .cddb and .cdindex files are generated unless suppressed by the
option -H. They contain suitable formatted entries for submission to
audio cd track title databases in the internet. The CDINDEX and CDDB(tm)
systems are currently supported. For more information please visit
www.musicbrainz.org and www.freedb.com.
.sp
Inf files:
.sp
The inf files are describing the sample files and the part from the audio cd,
it was taken from. They are a means to transfer information to a cd burning
program like wodim. For example, if the original audio cd had pre-emphasis
enabled, and icedax -T did remove the pre-emphasis, then the inf file has
pre-emphasis not set (since the audio file does not have it anymore), while
the .cddb and the .cdindex have pre-emphasis set as the original does.
.SH WARNING
.B IMPORTANT:
it is prohibited to sell copies of copyrighted material by noncopyright
holders. This program may not be used to circumvent copyrights.
The user acknowledges this constraint when using the software.
.SH BUGS
Generation of md5 checksums is currently broken.
.sp
Performance may not be optimal on slower systems.
.sp
The index scanner may give timeouts.
.sp
The resampling (rate conversion code) uses polynomial interpolation, which
is not optimal.
.sp
Icedax should use threads.
.sp
Icedax currently cannot sample hidden audio tracks (track 1 index 0).
.SH ACKNOWLEDGEMENTS
Thanks goto Project MODE (http://www.mode.net/) and Fraunhofer Institut f\*ur
integrierte Schaltungen (FhG-IIS) (http://www.iis.fhg.de/) for financial
support.
Plextor Europe and Ricoh Japan provided cdrom disk drives and cd burners
which helped a lot to develop this software.
Rammi has helped a lot with the debugging and showed a lot of stamina when
hearing 100 times the first 16 seconds of the first track of the Krupps CD.
Libparanoia contributed by Monty (Christopher Montgomery) xiphmont@mit.edu.
.SH AUTHOR
Heiko Eissfeldt heiko@colossus.escape.de
.PP
This manpage describes the program implementation of
.B
icedax
as shipped by the cdrkit distribution. See
.B
http://alioth.debian.org/projects/debburn/
for details. It is a spinoff from the original program cdda2wav as distributed
in the cdrtools package [1]. However, the cdrtools developers are not involved
in the development of this spinoff and therefore shall not be made responsible
for any problem caused by it. Do not try to get support for this program by
contacting the original authors.
.PP
If you have support questions, send them to
.PP
.B
debburn-devel@lists.alioth.debian.org
.br
.PP
If you have definitely found a bug, send a mail to this list or to
.PP
.B
submit@bugs.debian.org
.br
.PP
writing at least a short description into the Subject and "Package: cdrkit" into the first line of the mail body.

.SH DATE
26 Sep 2006

.SH SOURCES
.PP
.br
[1] Cdrtools 2.01.01a08 from May 2006, http://cdrecord.berlios.de

