.TH "LIST_AUDIO_TRACKS" "1" "Tue Feb 15 13:03:51 MST 2005" "" "list_audio_tracks"

.PP
.SH "NAME"
list_audio_tracks is an alias for icedax.
.PP
.SH "SYNOPSIS"
.PP
\fBlist_audio-tracks\fP
.PP
.SH "DESCRIPTION"
.PP
\fBlist_audio_tracks\fP equals to the invocation of icedax, so all the
arguments for the latter can be used.
.PP
.SH SEE ALSO
icedax(1)
.PP 
.SH "AUTHOR" 
.PP 
\fBicedax\fP was written by Heiko Eissfeldt and others.
.PP 
This manpage describes the program implementation of
.B
list_audio_tracks
as shipped by the cdrkit distribution. See
.B
http://alioth.debian.org/projects/debburn/
for details. It is a spinoff from the original program called cdda2wav
distributed by the cdrtools project. However, the cdrtools developers are not
involved in the development of this spinoff and therefore shall not be made
responsible for any problem caused by it. Do not try to get support for this
program by contacting the original authors.
.PP
If you have support questions, send them to
.PP
.B
debburn-devel@lists.alioth.debian.org
.br
.PP
If you have definitely found a bug, send a mail to this list or to
.PP
.B
submit@bugs.debian.org
.br
.PP
writing at least a short description into the Subject and "Package: cdrkit" into the first line of the mail body.
.PP
This manual page was written by Oleksandr Moskalenko
<malex@tagancha\&.org>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
